version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://learnerDB:LearnerOfMongoDb@learnerdb.p2czafh.mongodb.net/?retryWrites=true&w=majority&appName=LearnerDB
  db:
    image: mongo:latest
    volumes:
      - db_data:/data/db
volumes:
  db_data: